<?php
define('PLATFORM_INVITE_CODE',env('PLATFORM_INVITE_CODE','bcones'));
define('DIRECT_BONUS_RATIO',env('DIRECT_BONUS_RATIO',0.35));
define('LEVEL_BONUS_RATIO',env('LEVEL_BONUS_RATIO',0.05));
define('ACTIVATE_COST',env('ACTIVATE_COST',100));
define('PUBLIC_WALLET_ADDRESS',env('PUBLIC_WALLET_ADDRESS','0x'));
define('PUBLIC_WALLET_PWD',env('PUBLIC_WALLET_PWD','password'));